# Render deployment configuration file

services:
  # Frontend service
  - type: web
    name: memorix-frontend
    env: static
    buildCommand: npm install && npm run render-build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://memorix-api.onrender.com/api  # Replace with your backend URL
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
