# Render deployment configuration file

services:
  # Frontend service
  - type: web
    name: memorix-frontend
    env: static
    buildCommand: npm install --legacy-peer-deps && npm run render-build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://memorix-backend-wn9o.onrender.com/api  # Replace with your backend URL
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      # Serve sitemap.xml and robots.txt directly
      - type: rewrite
        source: /sitemap.xml
        destination: /sitemap.xml
      - type: rewrite
        source: /robots.txt
        destination: /robots.txt
      # For all other routes, serve index.html (SPA routing)
      - type: rewrite
        source: /**
        destination: /index.html
